### PR TITLE
login form (basic)

### LINKED ISSUE #45: Add Login Form

### PR DESCRIPTION
**Pull request by Arcaneghost24**
basic login form complete (minimal functionality, no true 'submission' yet

fixes #45

### CODE REVIEW

**Review by crestonesoftware — CHANGES_REQUESTED** [review]
How can this be tested?

**Comment by Arcaneghost24** [comment]
Repushed, should now see login link and the login form when clicked on.

**Review by josefalconGH — APPROVED** [review]
Changes viewable on my local branch 👍

**Comment by Arcaneghost24** [comment]
NOW it should actually be good

**Review by crestonesoftware — APPROVED** [review]

**Review by crestonesoftware — APPROVED** [review]

**Pull request merged**
